name: prototype-finance
channels:
- conda-forge
- defaults
dependencies:
- certifi=2018.4.16=py35_0
- pip=9.0.3=py35_0
- python=3.5.5=1
- setuptools=39.2.0=py35_0
- vs2015_runtime=14.0.25420=0
- wheel=0.31.0=py35_0
- wincertstore=0.2=py35_1
- pip:
  - apistar==0.5.40
  - chardet==3.0.4
  - click==6.7
  - idna==2.7
  - jinja2==2.10
  - markupsafe==1.0
  - pyyaml==3.12
  - requests==2.19.1
  - urllib3==1.23
  - werkzeug==0.14.1
  - whitenoise==3.3.1
